Writable:
  LogLevel: INFO

Service:
  Host: localhost
  Port: 59999
  StartupMsg: "CAN device service started.."
  RequestTimeout: "15s"

Device:
  ProfilesDir: "./res/profiles"
  DevicesDir: "./res/devices"

MessageBus:
  Optional:
    ClientId: "device-can"
